server:
  port: 19019

spring:

  # Fly configuration
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true
    user: postgres
    password: posgress
    url: jdbc:postgresql://localhost:5432/accounting?ApplicationName=accounting_ledger
    locations: classpath:db/migration


  # security
  security:
    basic:
      enabled: false
  # circular dependency
  main:
    allow-circular-references: true
  # Data source
  datasource:
    url: jdbc:postgresql://localhost:5432/accounting?ApplicationName=accounting_ledger
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      enable_lazy_load_no_trans: true
      ddl-auto: none
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: accounting_ledger

# Logging
logging:
  file:
    name: ${logging.file.path}/app-${spring.application.name}.log
    path: /data/logs/accounting
  level:
    root: info

# RabbitMQ
rabbitmq:
  queue:
    configurations:
      exchange: exchange.sync.accounting.requests
      x-message-ttl: 15000
      x-max-length: 50
      x-overflow: reject-publish-dlx
      queue-name: queue.sync.accounting.requests.inbound
      number-of-consumers: 5
      routing-key: key.async.accounting
      service-reply-timeout: 45000

# Okta authorization

okta:
  oauth2:
    issuer: https://dev-05562770.okta.com/oauth2/default
#    clientId: 0oa9j5cv18NcJWFd75d7
#    clientSecret: yl6g5tuy4i2284schHOMubulyg9fjvYPE2w0Diw9


# future Dated chron job

future:
  dated:
    cron:
      frequency: '* * * * * *'
